### ISSUE TITLE
Routelist

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#1]
## Value statement 
As a **climber** 
I need **a list of my urban climbing routes ** 
so that **get a quick overview about possible new projects** 
## Description 
<img width="384" alt="Routelist storyone" src="https://user-images.githubusercontent.com/52739584/69476163-a0ca5b00-0dd6-11ea-9ea3-874dd8b30882.png">
- It's a scrolling list of routes
- there are bars according to difficulty of routes displayed on each card
- There is a matching picture next to the route 

## Acceptance criteria
- [ ] routes are visually separated
- [ ] the page is scrollable
- [ ] every Route shows a picture, name, number of routes, bars according to difficulty of routes, heart icon and map icon

## Tasks
- [ ] create a json File of the routes
- [ ] create a Card Component in Storybook
- [ ] add Card Component in App
- [ ] testing

## Size
medium
