### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#17]
## Value statement 
As a **user** 
I need **my want my bookmarks to be saved after every session** 
so that **i can keep track of my climbing spots trough many sessions** 
## Description 
- the climbing Data is saved to a databased
## Acceptance criteria
- [ ]  the climbing Data is saved to a databased
- [ ] changes to bookmarks and isClimbed button are over multiple sessions
## Tasks
- [ ] implement database
- [ ] write get and post request
## Size
large
