### ISSUE TITLE
Create-new-form

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#18]
## Value statement
As a **explorer** 
I need **to be able share my new routes with my fellow climbingcommunity ** 
so that **a lot of people will enjoy my new route ** 
## Description 
- there is a new page with a form to create a new climbing spot
<img width="282" alt="Screenshot 2019-11-29 at 12 21 27" src="https://user-images.githubusercontent.com/52739584/69865884-ceb21280-12a2-11ea-849f-cbdd357e82f7.png">

## Acceptance criteria
- [ ] after filling out the form, the is a new climbing spot added to the app and to the database
## Tasks
- [ ] create new Page with a form
- [ ] add logic to form
- [ ] make new form appear in database
## Size
large
