### ISSUE TITLE
bookmarked and isClimbed overview page

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#19]
## Value statement
As a **Climber** 
I need **to see my favorite spots and climbed routes** 
so that **I can keep track of my climbs** 
## Description 
<img width="282" alt="Screenshot 2019-11-29 at 12 33 23" src="https://user-images.githubusercontent.com/52739584/69866474-7845d380-12a4-11ea-81df-b1ea2422bc24.png">

## Acceptance criteria
- [ ] there is a new page which shows all bookmarked and climbed spots and routes
## Tasks
- [ ] add a new page
- [ ] make bookmarked sites and climbed routes appear
## Size
medium
