### ISSUE TITLE
Detailed Route 

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#2]
## Value statement - a requirement, not a solution
As a **climber** 
I need **a detailed view on the climbing spot** 
so that **a can inform myself about that place** 
## Description

- on click on one spot there will be shown a detailed site of that place
- it contains a larger picture of the spot and a list of all the routes in that place

## Acceptance criteria
- [ ] the new detailed site is filling the whole page

## Tasks
- [ ] add click logic to cards
- [ ] create detailed-site on Storybook
- [ ] add detailed-site to App
- [ ] testing
## Size
medium
