### ISSUE TITLE
make routes highlite on click

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#20]
## Value statement 
As a **climber** 
I need **to know exactly where to climb** 
so that **I dont end up in a route I don't want to be** 
## Description 
- when clicking on a route on the detailed spot site, the matching route is highlighted on the image
## Acceptance criteria
- [ ] (when clicking on a route on the detailed spot site, the matching route is highlighted on the image
## Tasks
- [ ] add svg paths as routes on images
- [ ] add click logic to the routes
## Size
medium
