### ISSUE TITLE
Bookmark on Detailsite

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#21]
## Value statement
As a **user** 
I need **to also be able to bookmark my spots on the detailed site** 
so that **I dont need to change to the overview site first to bookmark** 

## Description
- the bookmark heart on the detailed spot site is also able to toggle
## Acceptance criteria
- [ ] you can toggle the heart, it is either red or empty
- [ ] the isBookmarked key value pair in the array is changing accordingly
## Tasks
- [ ] add togglelogic to heart
## Size
small
