### ISSUE TITLE
Make links and Location work without selected spot state

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#24]
## Value statement 
As a **user** 
I need **a way to share the climbing spots with my friends** 
so that **I can share my passion ** 
## Description 
- the url of the detailed site and to the map has the matching spot included. I can copy that link and reload the page without information getting lost. 
## Acceptance criteria
- [ ] the url of the detailed site and to the map has the matching spot included. I can copy that link and reload the page without information getting lost. 
## Tasks
- [ ] change links to include ids
- [ ] check for the url
- [ ] make matching spot appear
## Size
large
