### ISSUE TITLE
Bookmark Button

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#3]
## Value statement -
As a **user** 
I need **to bookmarks pots** 
so that **I have can see my favorite spots more easily** 
## Description 
- when clicking the heart icon, it will change color to show if bookmarked or un-bookmarked
## Acceptance criteria
- [ ] one can toggle hearticon on Click
- [ ] there is a isBookmarked key-value pair in the spots array changing accordingly
## Tasks
- [ ]  add toggle logic to heart icon
## Size
small
