### ISSUE TITLE
map starts at user position

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#33]
## Value statement 
As a **user** 
I need **to orientate myself fast** 
so that **i can start climbing earlier** 
## Description 
when navigating to the map, the default center is the user position
## Acceptance criteria
- [ ] when navigating to the map, the default center is the user position
## Tasks
- [ ] get user position
- [ ] set it to default center on map
## Size
medium
