### ISSUE TITLE
List only shows spots near me

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#34]
## Value statement - a requirement, not a solution
As a **user** 
I need **to get a quich overview which spots are near me** 
so that **i can start climbing earlier** 
## Description
the spotlist only shows spots which are in a 10 kilometer radius of the user, if the position of the map changes the spots on the list change accordingly
## Acceptance criteria
- [ ] only spots are shown which are represented on the map
## Tasks
- [ ] filter spots accoding to the location on user
- [ ] filter spots according to location on map
## Size
large
