### ISSUE TITLE
Modal has video

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#35]
## Value statement
As a **user** 
I need **to understand how to make a new route on the form** 
so that **i dont get confused** 
## Description
there is a little video playing, when the explanation modal is shown, explaining how to draw a new route
## Acceptance criteria
- [ ] video is running in a loop
- [ ] video starts by itself
## Tasks
- [ ] make video
- [ ] include video in modal
## Size
large
