### ISSUE TITLE
ascentbutton

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#4]
## Value statement - a requirement, not a solution
As a **user** 
I need **a way to mark my completed routes** 
so that **I can keep track of my personal achievements** 
## Description 
- on the detailed site there is a ascent-button next to each route
- when clicking on this button it is marked 'done'
## Acceptance criteria
- [ ] toggle-logic to acent button
- [ ] there is a isAscendet key-value pair in the spots array changing accordingly
## Tasks
- [ ] add Button to Routes
- [ ] add toggle logic to button
## Size
small
