### ISSUE TITLE
searchbar in spotlist

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#5]
## Value statement 
As a **user** 
I need **a way to filter my spotlist** 
so that **I can get Information quicker to my favorite spot* 
## Description
- there is a searchbar on top of the spotlist, which shows only the matching spots

## Acceptance criteria
- [ ] on input it filters the matching spots accordingly
## Tasks
- [ ] add searchbar to storybook
- [ ] add searchbar to app
- [ ] add filter logic to searchbar
## Size
small
