### ISSUE TITLE
climbing spots shown on map 

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#8]
## Value statement 
As a **user** 
I need **the nearest climbing spots shown on a map** 
so that **I can orientate myself and make an informed decision of where to go next** 
## Description
- the map shows the climbing spot
- when clicking on them there are some detailes shown
<img width="379" alt="Screenshot 2019-11-23 at 11 47 05" src="https://user-images.githubusercontent.com/52739584/69477475-0888a200-0de7-11ea-8f57-5ae99966a511.png">

## Acceptance criteria
- [ ] when clicking on on spot, one can see the details of that spot
## Tasks
- [ ] add spot geographical points to map
- [ ] add logic, that details are shown
## Size
large
