### ISSUE TITLE
navigation footer

### ISSUE THREAD

**Issue by srmnq** [srmnq/urbanclimbing#9]
## Value statement
As a **user** 
I need **a simple way to navigate between map and list format** 
so that **I can choose what I want to see** 
## Description
- there is a navigation footer on the bottom of the map and the list site, which leads to the sites
## Acceptance criteria
- [ ] the navigation footer is on the bottom of the two sites
- [ ] when clicking on them it leads to the map or list respectively
## Tasks
- [ ] add footer to storybook
- [ ] add footer to app
- [ ] add logic to navigation
## Size
small
